/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:fc0fce81-a984-4b84-bbee-7d59c97827d9",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_DMuZBMCj5",
    "aws_user_pools_web_client_id": "1mnb4juh3hi0bakfgmhpqflir4",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://7bzy6hivmvhi5hzcfiribtqo5a.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "menu-item-images205815-prod",
    "aws_user_files_s3_bucket_region": "ap-northeast-2"
};


export default awsmobile;
