/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:8ccc08c0-f817-439a-ac2d-8b4d963c546e",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_5UgFOCrcb",
    "aws_user_pools_web_client_id": "4l7dqc94jmo31652u86a0ilkq7",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://lq4x6u7uczcopfgrnmsqcgexii.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "menu-item-images05236-dev",
    "aws_user_files_s3_bucket_region": "ap-northeast-2"
};


export default awsmobile;
