/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-northeast-2",
  aws_cognito_identity_pool_id: "ap-northeast-2:23a07b4b-d392-4ffc-be02-b0002b7b0811",
  aws_cognito_region: "ap-northeast-2",
  aws_user_pools_id: "ap-northeast-2_0GsmAilzk",
  aws_user_pools_web_client_id: "4gfsqb52rc52m9etnhqi7ipk82",
  oauth: {},
  aws_appsync_graphqlEndpoint:
    "https://xhy6ctzdn5g43gwordhaidpbpe.appsync-api.ap-northeast-2.amazonaws.com/graphql",
  aws_appsync_region: "ap-northeast-2",
  aws_appsync_authenticationType: "AWS_IAM",
  aws_user_files_s3_bucket: "menu-item-images205636-test",
  aws_user_files_s3_bucket_region: "ap-northeast-2",
};

export default awsmobile;
